# Generated by Django 3.0.6 on 2020-05-29 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['title', 'description'],
            },
        ),
        migrations.CreateModel(
            name='Training_Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Generic', max_length=50)),
                ('slug', models.CharField(default=1, max_length=50)),
                ('description', models.CharField(default='description', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Domains',
            },
        ),
        migrations.CreateModel(
            name='Writeup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=50)),
                ('image', models.URLField(verbose_name='Image')),
                ('description', models.CharField(max_length=200)),
                ('url', models.URLField(verbose_name='Github URL')),
                ('year', models.IntegerField(default=2020)),
                ('author', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Training_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Basic Skill', max_length=50)),
                ('description', models.CharField(default='description', max_length=200)),
                ('slug', models.CharField(default=1, max_length=50)),
                ('cat_description', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Category_Description', verbose_name='Cat')),
                ('domain', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Training_Domain', verbose_name='Domain')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=50)),
                ('content', models.TextField()),
                ('slug', models.SlugField(default=1)),
                ('cat_description', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Category_Description', verbose_name='Cat')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Training_Category', verbose_name='Category')),
            ],
        ),
    ]
