# Generated by Django 3.0.6 on 2020-05-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_writeup_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeup',
            name='url',
        ),
        migrations.AddField(
            model_name='writeup',
            name='content',
            field=models.TextField(default=1),
        ),
    ]
