# Generated by Django 3.0.6 on 2020-05-29 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20200528_2008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_description',
            options={'ordering': ['title'], 'verbose_name_plural': 'Category Descriptions'},
        ),
        migrations.AddField(
            model_name='training',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
