# Generated by Django 3.0.6 on 2020-05-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200529_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeup',
            name='slug',
            field=models.SlugField(default=1),
        ),
    ]
