# Generated by Django 3.0.6 on 2020-05-06 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
