# Generated by Django 3.0.6 on 2020-05-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_tutorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writeup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(verbose_name='Image')),
                ('description', models.CharField(max_length=200)),
                ('url', models.URLField(verbose_name='Github URL')),
            ],
        ),
    ]
