# Generated by Django 3.0.6 on 2020-05-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_writeup'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeup',
            name='title',
            field=models.CharField(default='title', max_length=50),
        ),
    ]
