# Generated by Django 3.0.6 on 2020-05-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_writeup_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeup',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
