# Generated by Django 3.0.6 on 2020-05-25 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_writeup_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training_Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Generic', max_length=50)),
                ('slug', models.CharField(default=1, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Domains',
            },
        ),
        migrations.AlterField(
            model_name='writeup',
            name='title',
            field=models.CharField(default='Title', max_length=50),
        ),
        migrations.CreateModel(
            name='Training_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Basic Skill', max_length=50)),
                ('description', models.CharField(default='description', max_length=200)),
                ('domain', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Training_Domain', verbose_name='Domain')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=50)),
                ('content', models.TextField()),
                ('slug', models.CharField(default=1, max_length=50)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Training_Category', verbose_name='Category')),
            ],
        ),
    ]
