# Generated by Django 3.0.6 on 2020-05-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200525_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_domain',
            name='description',
            field=models.CharField(default='description', max_length=200),
        ),
    ]
