# Generated by Django 3.0.6 on 2020-05-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_training_domain_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_category',
            name='slug',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
