# Generated by Django 3.0.6 on 2020-05-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_training_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='slug',
            field=models.SlugField(default=1),
        ),
    ]
