# Generated by Django 3.0.6 on 2020-05-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200528_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Long_Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['description'],
            },
        ),
        migrations.AddField(
            model_name='training',
            name='long_description',
            field=models.ManyToManyField(to='main.Long_Description'),
        ),
    ]
