# Generated by Django 3.0.6 on 2020-05-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200528_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_category',
            name='long_description',
            field=models.ManyToManyField(to='main.Long_Description'),
        ),
    ]
