# Generated by Django 3.0.6 on 2020-05-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_training_category_long_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='long_description',
            options={'ordering': ['title', 'description']},
        ),
        migrations.AddField(
            model_name='long_description',
            name='title',
            field=models.CharField(default='Title', max_length=50),
        ),
    ]
