# Generated by Django 3.0.6 on 2020-05-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200528_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='long_description',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
