# Generated by Django 3.0.6 on 2020-05-28 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_training_domain_long_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training_category',
            old_name='long_description',
            new_name='long_descr',
        ),
        migrations.RenameField(
            model_name='training_domain',
            old_name='long_description',
            new_name='long_descr',
        ),
        migrations.RemoveField(
            model_name='training',
            name='long_description',
        ),
    ]
