# Generated by Django 3.0.6 on 2020-05-28 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200528_1815'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Long_Description',
            new_name='Category_Description',
        ),
        migrations.RenameField(
            model_name='training_category',
            old_name='long_descr',
            new_name='cat_description',
        ),
        migrations.RemoveField(
            model_name='training_domain',
            name='long_descr',
        ),
        migrations.AddField(
            model_name='training',
            name='cat_description',
            field=models.ManyToManyField(to='main.Category_Description'),
        ),
    ]
