# Generated by Django 3.0.6 on 2020-05-28 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200528_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='cat_description',
        ),
        migrations.RemoveField(
            model_name='training_category',
            name='cat_description',
        ),
        migrations.AddField(
            model_name='training_category',
            name='cat_description',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Category_Description', verbose_name='Cat'),
        ),
    ]
