# Generated by Django 3.0.6 on 2020-05-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_training_cat_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_description',
            name='description',
            field=models.TextField(),
        ),
    ]
